### ISSUE TITLE
Something goes wrong with displaying signature help

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-dockerfile#3]
```
Error handling server payload
Traceback (most recent call last):
  File "/Users/../Packages/LSP/plugin/core/rpc.py", line 215, in receive_payload
    self.response_handler(payload)
  File "/Users/../Packages/LSP/plugin/core/rpc.py", line 236, in response_handler
    handler(result)
  File "/Users/../Packages/LSP/plugin/signature_help.py", line 103, in <lambda>
    lambda response: self.handle_response(response, point))
  File "/Users/../Packages/LSP/plugin/signature_help.py", line 107, in handle_response
    self._help = create_signature_help(response)
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 179, in create_signature_help
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 179, in <genexpr>
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 114, in parse_signature_information
    paren_bounds = parse_signature_label(signature_label, param_infos)
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 84, in parse_signature_label
    if signature_label[current_index] != ',':
IndexError: string index out of range
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/153197/80227262-ae1d9700-864d-11ea-8437-51bfe6123322.gif)

**Comment by rwols** [comment]
Interesting. Is it a signature with 0 arguments?

**Comment by rwols** [comment]
Looks like we assume that the `signature_label` string has the form `... , ...` somehow. That's a bug for us :)
